// Generated by https://quicktype.io

export interface QuestionResponse {
    role:    string;
    content: string[];
}

// export enum Role {
//     Assistant = "assistant",
//     User = "user",
// }
